name: usafe_front_end
description: "USafe - Intelligent Personal Safety App"
publish_to: "none"
version: 1.0.0+1

environment:
  # Minimum version 2.17.0 required for 'super.key'
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Core Functionality
  flutter_contacts: ^1.1.9
  geolocator: ^13.0.2
  url_launcher: ^6.3.1
  intl: ^0.19.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.5

  # Maps & Payment
  flutter_stripe: ^9.0.0
  http: ^1.2.0
  google_sign_in: ^6.1.2
  google_maps_flutter: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Ensure these files exist in your 'assets' folder!
  assets:
    - assets/usafe_logo.png
    - assets/google.jpg
