name: usafe_front_end
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_stripe: ^9.0.0
  http: ^1.0.0
  cupertino_icons: ^1.0.8
  flutter_contacts: ^1.1.9
  geolocator: ^13.0.2
  url_launcher: ^6.3.1
  intl: ^0.19.0
  google_maps_flutter: ^2.10.0
  permission_handler: ^11.3.1
  dependencies:
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/usafe_logo.png
