name: usafe_front_end
description: "USafe - Intelligent Personal Safety App"
publish_to: "none"

version: 1.0.0+1

environment:
  # Supporting Dart 3.0.0 and above as per your environment
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Core Functionality Packages
  flutter_contacts: ^1.1.9
  geolocator: ^13.0.2
  url_launcher: ^6.3.1
  intl: ^0.19.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/usafe_logo.png
    - assets/google.jpg
