name: usafe_fresh
description: "USafe - Intelligent Personal Safety App"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_contacts: ^1.1.9+2
  permission_handler: ^11.3.1
  geolocator: ^12.0.0
  url_launcher: ^6.3.2
  intl: ^0.20.2
  shared_preferences: ^2.5.3

  flutter_stripe: 10.1.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/usafe_logo.png
    - assets/google.jpg
